version: '3.8'

services:
  login-microservice:
    build: ./login-microservice
    command: gunicorn cloudproj.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./login-microservice:/code
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOST: cloudproj-db.c0lhyehslrbj.ap-southeast-1.rds.amazonaws.com
      DATABASE_NAME: cloudproj
      DATABASE_USER: root
      DATABASE_PASSWORD: root

  home-microservice:
    build: ./home-microservice
    command: gunicorn cloudproj.wsgi:application --bind 0.0.0.0:8001
    volumes:
      - ./home-microservice:/home-code
    ports:
      - "8001:8001"
    environment:
      DATABASE_HOST: cloudproj-db.c0lhyehslrbj.ap-southeast-1.rds.amazonaws.com
      DATABASE_NAME: cloudproj
      DATABASE_USER: root
      DATABASE_PASSWORD: root

  search-microservice:
    build: ./search-microservice
    command: gunicorn cloudproj.wsgi:application --bind 0.0.0.0:8002
    volumes:
      - ./search-microservice:/search-code
    ports:
      - "8002:8002"
    environment:
      DATABASE_HOST: cloudproj-db.c0lhyehslrbj.ap-southeast-1.rds.amazonaws.com
      DATABASE_NAME: cloudproj
      DATABASE_USER: root
      DATABASE_PASSWORD: root

  create-microservice:
    build: ./create-microservice
    command: gunicorn cloudproj.wsgi:application --bind 0.0.0.0:8003
    volumes:
      - ./create-microservice:/create-code
    ports:
      - "8003:8003"
    environment:
      DATABASE_HOST: cloudproj-db.c0lhyehslrbj.ap-southeast-1.rds.amazonaws.com
      DATABASE_NAME: cloudproj
      DATABASE_USER: root
      DATABASE_PASSWORD: root
